namespace Shared.Enums
{
    public enum ViewType
    {
        LoginView,
        AdminView,
        CashierView,
        ActivityHistoryView,
        CheckHistoryView,
        AddUserView,
        AddFoodView,
        AddDrinkView,
        AddModificatorView,
        EditUserView,
        EditFoodView,
        EditDrinkView,
        EditModificatorView,
        ColdDrinkListView,
        DessertListView,
        FishListView,
        GarnishListView,
        HotDrinkListView,
        JuiceListView,
        MealListView,
        MeatDishListView,
        PastaListView,
        PizzaListView,
        SaladListView,
        SauceListView,
        SnackListView,
        SoupListView       
    }
}